services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $requestStack: '@request_stack'
            $maxRepeatCount: '%cgoit_calendar_extended.max_repeat_count%'

    Cgoit\CalendarExtendedBundle\:
        resource: ../src/*
