services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $db: '@database_connection'

    Cgoit\CalendarExtendedBundle\:
        resource: ../src/*
