services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $db: '@database_connection'
            $requestStack: '@request_stack'
            $maxRepeatCount: '%cgoit_calendar_extended.max_repeat_count%'
            $maxExceptionsCount: '%cgoit_calendar_extended.exceptions.max_count%'
            $exceptionsMoveDays: '%cgoit_calendar_extended.exceptions.move_days%'
            $exceptionsMoveTimes: '%cgoit_calendar_extended.exceptions.move_times%'
            $arrFilterFields: '%cgoit_calendar_extended.filter_fields%'

    Cgoit\CalendarExtendedBundle\:
        resource: ../src/*

    calendar_extended.mcw.callbacks:
        class: Cgoit\CalendarExtendedBundle\EventListener\DataContainer\CalendarEventsMCWCallbacks
        public: true

    calendar_extended.module.callbacks:
        class: Cgoit\CalendarExtendedBundle\EventListener\DataContainer\ModuleCallbacks
        public: true

    Cgoit\CalendarExtendedBundle\Migration\RenameFieldsMigration:
        tags:
            - { name: contao.migration }

    Cgoit\CalendarExtendedBundle\Migration\CopyHolidayCalendarsMigration:
        tags:
            - { name: contao.migration }

    Cgoit\CalendarExtendedBundle\Migration\FixRepeatFixedDatesMigration:
        tags:
            - { name: contao.migration }
